FROM node:10.11.0-alpine

RUN mkdir -p /app
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . ./

EXPOSE 4200
ENTRYPOINT ["./node_modules/.bin/ng"]
CMD ["serve", "--host", "0.0.0.0"]
